version: 0.2
environment_variables:
  plaintext:
    CHILD_TEMPLATES: |
      sns.yml
      s3.yml
phases:
  build:
    commands:
        aws s3 cp --recursive ./chaildstack/ s3://artifactbucket-cicd-test/
#       aws codepipeline start-pipeline-execution --name Iac-pipeline
