AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  TestRegion:
    Type: String
Resources:
  s3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://code-build-input-bucket1.s3.amazonaws.com/s3.json
  sns:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://code-build-input-bucket1.s3.amazonaws.com/sns.json
